services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:19093
      - --advertise-kafka-addr
      - INTERNAL://redpanda:9093,EXTERNAL://localhost:19093
    ports:
      - "19093:19093"

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - minio_data:/data

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: logpipe_user
      POSTGRES_PASSWORD: logpipe_password
      POSTGRES_DB: logpipe_db
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  minio_data:
  pg_data:
